BUGFIX Name of <class>, <const> can conflict with namespace name
Example:
ProjectX.soodaproject (part of):
<sooda-project xmlns="http://www.sooda.org/schemas/SoodaProject.xsd">
    <schema-file>DBSchema.xml</schema-file>
    <language>c#</language>
    <output-namespace>ProjectX.BusinessObjects</output-namespace>
    <output-path>src/ProjectX.BusinessObjects</output-path>
    <base-class-name>ProjectX.BusinessObjects.SoodaObjectHelper</base-class-name>
...
</sooda-project>

DBSchema:
<?xml version="1.0" encoding="utf-8"  ?>
<schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.sooda.org/schemas/SoodaSchema.xsd">
    <datasource name="default" type="Sooda.Sql.SqlDataSource" />

    <class name="AnyClass" cardinality="Large">
        <table name="AnyTable">
            <field name="Id" dbcolumn="id" type="Integer" primaryKey="true" nullable="false"></field>
            ...
        </table>
        <const name="ProjectX" key="1" />
    </class>
...
</xml>

Your _Stubs.csx cannot be compiled - there is a conflict of static object name and namespace name:
namespace ProjectX.BusinessObjects.Stubs {
  using ProjectX.BusinessObjects;
...
  public class AnyClass_Stub : ProjectX.BusinessObjects.SoodaObjectHelper {
    private static IPrimaryKeyGenerator keyGenerator = new Sooda.ObjectMapper.KeyGenerators.TableBasedGenerator("AnyClass", ProjectX.BusinessObjects._DatabaseSchema.GetSchema().GetDataSourceInfo("default"));
...
    public static AnyClass Load(SoodaTransaction tran, int objectId) {
      AnyClass retVal = ProjectX.BusinessObjects.Stubs.AnyClass_Stub.GetRef(tran, objectId); // 
      Sooda.ObjectMapper.SoodaObjectImpl.LoadAllData(retVal);
      return retVal;
    }
...
    public static AnyClass ProjectX {
      get {
        return AnyClass_Stub.GetRef(1);
      }
    }
...
}
Compilation error:
     ProjectX.BusinessObjects\Stubs\_Stubs.csx(...,134): error CS0117: ProjectX.BusinessObjects.AnyClass' does not contain a definition for 'BusinessObjects'
     ProjectX.BusinessObjects\Stubs\_Stubs.csx(...,34): error CS0117: ProjectX.BusinessObjects.AnyClass' does not contain a definition for 'BusinessObjects'

Fix: use alias for namespace, the same parts of code will look like:
namespace ProjectX.BusinessObjects.Stubs {
  using ProjectXBusinessObjects = ProjectX.BusinessObjects;
...
  public class AnyClass_Stub : ProjectX.BusinessObjects.SoodaObjectHelper {
    private static IPrimaryKeyGenerator keyGenerator = new Sooda.ObjectMapper.KeyGenerators.TableBasedGenerator("AnyClass", ProjectXBusinessObjects._DatabaseSchema.GetSchema().GetDataSourceInfo("default"));
...
    public static AnyClass Load(SoodaTransaction tran, int objectId) {
      AnyClass retVal = AnyClass_Stub.GetRef(tran, objectId); // 
      Sooda.ObjectMapper.SoodaObjectImpl.LoadAllData(retVal);
      return retVal;
    }
...
    public static AnyClass ProjectX {
      get {
        return AnyClass_Stub.GetRef(1);
      }
    }
...
}